services:
    app.admin.terrain:
        class: WCS\CoavBundle\Admin\TerrainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Vols", label: "Terrain" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Terrain
            - ~
    app.admin.flight:
        class: WCS\CoavBundle\Admin\FlightAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Vols", label: "Flight" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Flight
            - ~    
    app.admin.plane:
        class: WCS\CoavBundle\Admin\PlaneModelAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Vols", label: "PlaneModel" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\PlaneModel
            - ~
    app.admin.reservation:
        class: WCS\CoavBundle\Admin\ReservationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Reservations", label: "Reservation" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Reservation
            - ~
    app.admin.user:
        class: WCS\CoavBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Reservations", label: "User" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\User
            - ~