wcs_coav_user:
    resource: "@WCSCoavBundle/Controller/UserController.php"
    type:     annotation

wcs_coav_reservation:
    resource: "@WCSCoavBundle/Controller/ReservationController.php"
    type:     annotation

wcs_coav_flight:
    resource: "@WCSCoavBundle/Controller/FlightController.php"
    type:     annotation

wcs_coav_terrain:
    resource: "@WCSCoavBundle/Controller/TerrainController.php"
    type:     annotation

wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
