<?php

namespace WCS\CoavBundle\Repository;

/**
 * nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class nameRepository extends \Doctrine\ORM\EntityRepository
{
}
